### ISSUE TITLE
Drop log bucket default

### ISSUE THREAD

**Issue by ddriddle** [techservicesillinois/terraform-aws-cloudfront-distribution#10]
To make this code more portable I think we should consider making `var.log_bucket` mandatory, and drop the default: `local.default_log_bucket`. We should specify this value in `common.tfvars`

**Comment by JonRoma** [comment]
@ddriddle, would your suggestion still work given that Terraform is now being stricter about variables that aren't used in modules below the `common.tfvars`?

**Comment by ddriddle** [comment]
Yes. We have a shared `common.tfvars` for our CloudFront configs today. Terraform's changes are not a problem in general for us because of the way we have things laid out.

**Comment by JonRoma** [comment]
A null default for `log_bucket` was implemented in #6ded1e.
