### ISSUE TITLE
Use a lookup to avoid hardcoding lambda versions?

### ISSUE THREAD

**Issue by ddriddle** [techservicesillinois/terraform-aws-cloudfront-distribution#15]
@JonRoma unfortunately testing has shown that It is not possible to use $LATEST in variable cloudfront_lambda_origin_request_arn. I think we should consider using a data lookup to avoid specifying the version.

See related issue: https://github.com/techservicesillinois/terraform-aws-cloudfront-lambda-directory-index/issues/9

**Comment by JonRoma** [comment]
I think this also relates to #20.

**Comment by ddriddle** [comment]
This ticket is not related to #20. This ticket is obsolete and I will close it.

Our module currently supports looking up the latest version of a Lambda function using an alias. The version does not need to be specified as the documentation demonstrates. What still can not be done is use $LATEST. That is a limitation of CloudFront that we can not change.
