### ISSUE TITLE
[cloudfront-distribution] Do not hardcode environment "as-test" domain etc in hostname

### ISSUE THREAD

**Issue by akibare999** [techservicesillinois/terraform-aws-cloudfront-distribution#9]
The hostname should only contain the "short" name above the domain, not including any "as-test" "as-dev" type domain parts. Those must come from some other configuration specific to each environment's repository.

The reason is, we want to take the file existing in the as-aws-test repository and move it to production WITHOUT any sort of editing of any terragrunt source, it all needs to work right out of the box after we (or a process!) move the commits over.

**Comment by JonRoma** [comment]
Can't reproduce with current module version.
